name: DYG
channels:
  - xformers
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.6
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.9.20
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xformers=0.0.22.post7
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.0.1
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - argparse==1.4.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - chardet==5.2.0
      - click==8.1.7
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - diffusers==0.29.2
      - docstring-parser==0.16
      - einops==0.8.0
      - embreex==2.17.7.post6
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.2
      - ffmpy==0.4.0
      - flatbuffers==25.2.10
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - gdown==5.2.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kaleido==0.1.0
      - kiui==0.2.14
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - lxml==5.3.1
      - manifold3d==3.0.1
      - mapbox-earcut==1.0.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - msgpack==1.1.0
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==1.24.1
      - objprint==0.2.3
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.3
      - peft==0.10.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - plyfile==1.1
      - pooch==1.8.2
      - portalocker==2.10.1
      - protobuf==5.29.3
      - psutil==6.0.0
      - pycollada==0.9
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyliblzfse==0.4.1
      - pymatting==1.1.13
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.9.11
      - rembg==2.0.59
      - rich==13.9.2
      - rpds-py==0.23.1
      - rtree==1.3.0
      - ruff==0.6.9
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.12.0
      - semantic-version==2.10.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.40.0
      - svg-path==6.3
      - tenacity==9.0.0
      - tifffile==2024.8.30
      - timm==1.0.11
      - tokenizers==0.20.1
      - tomlkit==0.12.0
      - tqdm==4.66.5
      - transformers==4.45.2
      - trimesh==4.5.3
      - typeguard==4.4.2
      - typer==0.12.5
      - typing==3.7.4.3
      - tyro==0.9.16
      - tzdata==2024.2
      - uvicorn==0.32.0
      - varname==0.13.5
      - vhacdx==0.0.8.post2
      - websockets==12.0
      - xatlas==0.0.9
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - zipp==3.20.2
      - ./submodules/diff-gaussian-rasterization-with-bbox-mask
      - ./submodules/simple-knn
      - ./submodules/pytorch3d
      - -e ./viser
